#!/usr/bin/env bash

hc() { herbstclient "$@"; }
export -f hc

export TERMINAL=alacritty
export LAUNCHER=dmenu_run

hc emit_hook reload

# Execute configs
CONFIG=~/.config/herbstluftwm

$CONFIG/keybinds
$CONFIG/theme
$CONFIG/misc

# Autostart

~/.fehbg
