#!/usr/bin/env bash

# Init

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1

# General

hc set frame_gap 0
hc set frame_transparent_width 0
hc set frame_bg_transparent 1
hc set always_show_frame off
hc set frame_border_width 0
hc set frame_padding 0

hc set window_gap 15

# Colors

hc attr theme.active.color '#586d62'
hc attr theme.normal.color '#2c302e'
hc attr theme.urgent.color '#b56e50'

# Padding

hc attr theme.padding_top 20
